sudo: required
services:
  - docker

before_install:
  - source .env.sh
  - docker-compose build

language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      
install:
  - pip install -r src/app/requirements.txt

script:
  - pytest tests
