version: '3.3'
services:

  pyapp:
    build: 
      context: ./app
      dockerfile: Dockerfile_app
      
    #restart: always
    container_name: pyapp-container
    env_file: app/.env
    ports: 
    # these environment variables have to be set in calling os shell
    # can't be read from .env file
    #test with docker-compose config
    - ${PY_PORT}:${PY_PORT}
      
    volumes:
    - ./app:/usr/home/app
    
    # networks:
    # - app-pyapp-network
    # command:
    #   - "sleep"
    #   - "10000"
    command: 
      - "python"
      - "/usr/home/app/app.py"

  opa:
    build: 
      context: ./opa
      dockerfile: Dockerfile_opa

    container_name: opa-container
    expose: 
      - 8181
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    volumes:
       - ./opa/rego:/usr/home/rego
    
    #command:
      # - "sleep"
      # - "10000"
    command:
      - "run"
      - "-s"
      - "-w"
      - "rego/product_policy_data.json"
      - "rego/product_policy.rego"
    # networks:
    # - app-pyapp-network

# networks:
#   app-pyapp-network:
#     driver: bridge
  