FROM python:3-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /usr/home/

COPY ./requirements.txt ./app/
RUN pip install --no-cache-dir -r ./app/requirements.txt

COPY . ./app/

EXPOSE 5000
